XBotInterface:
    urdf_path: $(rospack find doosan_xbot2_config)/urdf/h2515.urdf
    srdf_path: $(rospack find doosan_xbot2_config)/srdf/h2515.srdf

ModelInterface:
  model_type: "RBDL"

# hal
xbotcore_device_configs:
    sim: $(rospack find doosan_xbot2_config)/hal/gz.yaml
    dummy: $(rospack find doosan_xbot2_config)/hal/dummy.yaml

# threads
xbotcore_threads:
    rt_main:  {sched: fifo , prio: 99, period: 0.01}
    nrt_main: {sched: other, prio: 0 , period: 0.01}


# plugins
xbotcore_plugins:

    # Homing plugin is provided togheter with the xbot 
    # binaries but the source code is visible at 
    # https://github.com/ADVRHumanoids/xbot2_examples/tree/master/src/homing_example
    homing:
        thread: rt_main
        type: homing
        params:
            qhome: {value: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], type: Eigen::VectorXd}

    ros_io: {thread: nrt_main, type: ros_io, params: {publish_tf: {type: bool, value: true}}}
    ros_control: {thread: nrt_main, type: ros_control, params: {autostart: {type: bool, value: true}}}

    periodic_motion:
        thread: rt_main
        type: periodic_motion
        params:
           q_home_start: {value: [0, 0.5, -0.5, 0, 0, 0], type: Eigen::VectorXd}
           q_home_end:   {value: [0, -1.0, -1.0, 0, -1.57, -1.57], type: Eigen::VectorXd}
           time: {value: 20.0, type: double}


# global parameters
# additional parameters that don't relate to any plugin 
xbotcore_param:
    /xbot/hal/joint_safety/filter_autostart: {value: true, type: bool}
    /xbot/hal/joint_safety/filter_cutoff_hz: {value: 1.0, type: double}
    /xbot/hal/enable_safety: {value: true, type: bool}
    /xbot_internal/ros_io/call_timeout: {value: 1.0, type: chrono}
    /rt_main/memory_hooks: {value: true, type: bool}






