solver_options:
    regularization: 1e-2
    back_end: qpoases

stack:
  - [tcp]
  - [postural]

constraints:
  - jlim
  - vlim

jlim:
  type: JointLimits
  limits:
    # arm_joint_3: [0, 0]

vlim:
  type: VelocityLimits
  limits: 3.0

tcp:
  type: Cartesian
  lambda: 0.1
  distal_link: link6
  use_local_subtasks: true

postural:
  type: Postural
  lambda: 0.1
